version: 1
validation: sovereign
build:
  main: ./cmd/safrochaind
accounts: 
- name: alice
  coins:
  - 50000safro
  - 3000000000000000stake
  mnemonic: raise decline figure capable tribe normal mixed vast couch remember simple decline puppy buyer soul glove brush guilt north nurse edit bitter frame bind
- name: bob
  coins:
  - 10000safro
  - 100000000stake
  mnemonic: struggle since inmate safe logic kite tag web win stay security wonder
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5safro
  - 100000stake
validators:
- name: alice
  bonded: 200000000000000stake
genesis:
  chain_id: cosmoshub-12

